version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f2y3m7g6
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t recipes .
      - docker tag recipes:latest public.ecr.aws/f2y3m7g6/recipes:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/f2y3m7g6/recipes:latest
